### PR TITLE
Make formset sorting work with Django 1.10

### PR DESCRIPTION
**Pull request by unaizalakain**
Formset sorting was done by extracting the field to sort by from each formset
item, creating a `[(field, formset_item)]` list and sorting that list. For this
to work `formset_item` (instance of `InlineAdminForm`) had to be comparable. I
don't know about earlier versions, but at least with Django 1.10 it isn't.

Sorting is now done by partitioning the items that can be sorted from the ones
that can't, sorting the ones that can be sorted, and returning the sorted ones
followed by the unsortable ones.

### CODE REVIEW

**Comment by sehmaschine** [comment]
@unaizalakain this PR does not work. if I submit an inline formset with updated positions and I have an error within that formset, the ordering is not correct. happy to review an updated PR.

**Comment by unaizalakain** [comment]
@sehmaschine I might be missing something, but that didn't work before neither: the `formsetsort` template isn't called at all when submitting an erroneous formset.

**Comment by sehmaschine** [comment]
@unaizalakain what do you mean with the formsetsort template? and yes, it has been working and it is still working.

**Comment by unaizalakain** [comment]
@sehmaschine Maybe I didn't understand.

Using django-grappelli 2.9 and django 1.10, I load a model's change page, change the order of the elements in its related inline formset, change a field in the formset so that it throws an error, and "Save and continue editing". The result is that the object is not saved and that the order of the inline objects gets messed up.

And I get exactly the same behaviour once applied the PR. But I think I didn't understand your test case :-/

**Comment by sehmaschine** [comment]
@unaizalakain that´s exactly what I do ... but the order is only messed up with the PR applied (it works for me without your PR). can you do a test with the branch stable/2.9.x and django 1.10?

besides, if the sorting is messed up with your PR, you do agree that the PR is not exactly what we need ... right? or did I miss something?

**Comment by unaizalakain** [comment]
@sehmaschine that's what I did, I tested with stable/2.9.x and django 1.10.

But anyway, my PR only changes the `formsetsort` function. And, as you can test, that function is not called at all when going through the test. So I can't understand how it would mess up the order.

**Comment by unaizalakain** [comment]
@sehmaschine  Also to be noted, when `formsetsort` *is* executed (when the inline objects are correctly saved), the order is maintained.

**Comment by sehmaschine** [comment]
@unaizalakain see https://github.com/sehmaschine/django-grappelli/blob/master/grappelli/templates/admin/edit_inline/stacked.html#L17 ... the function is called every time the inline templates are used.

**Comment by unaizalakain** [comment]
@sehmaschine Oh my, my apologies: I modified the source path for grappelli and didn't reload my development server! I tried testing with stable/2.9.x and django 1.10 again, this is the traceback I get (which motivates the PR):

    Traceback (most recent call last):
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
        response = get_response(request)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
        response = self.process_exception_by_middleware(e, request)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
        response = response.render()
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/response.py", line 109, in render
        self.content = self.rendered_content
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/response.py", line 86, in rendered_content
        content = template.render(context, self._request)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
        return self.template.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 208, in render
        return self._render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
        return self.nodelist.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 994, in render
        bit = node.render_annotated(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
        return self.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/loader_tags.py", line 174, in render
        return compiled_parent._render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
        return self.nodelist.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 994, in render
        bit = node.render_annotated(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
        return self.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/loader_tags.py", line 174, in render
        return compiled_parent._render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
        return self.nodelist.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 994, in render
        bit = node.render_annotated(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
        return self.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/loader_tags.py", line 70, in render
        result = block.nodelist.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 994, in render
        bit = node.render_annotated(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
        return self.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/loader_tags.py", line 70, in render
        result = block.nodelist.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 994, in render
        bit = node.render_annotated(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
        return self.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
        nodelist.append(node.render_annotated(context))
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
        return self.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/loader_tags.py", line 210, in render
        return template.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 210, in render
        return self._render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
        return self.nodelist.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 994, in render
        bit = node.render_annotated(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
        return self.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/defaulttags.py", line 510, in render
        return self.nodelist.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 994, in render
        bit = node.render_annotated(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
        return self.render(context)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/defaulttags.py", line 159, in render
        values = self.sequence.resolve(context, True)
      File "/home/unai/.virtualenvs/amv2/lib/python3.5/site-packages/django/template/base.py", line 739, in resolve
        new_obj = func(obj, *arg_vals)
      File "/home/unai/devel/django-grappelli/grappelli/templatetags/grp_tags.py",line 138, in formsetsort
        sorted_list.sort()
    TypeError: unorderable types: InlineAdminForm() < InlineAdminForm()

**Comment by unaizalakain** [comment]
@sehmaschine `formsetsort` is trying to sort a list of `(int, InlineAdminForm)` tuples. This works correctly provided there are no two equal `int`s.

**Pull request closed without merging**
