### PR TITLE
Fix Django 1.10 warning

### PR DESCRIPTION
**Pull request by GuillaumeCisco**
Fix Django 1.10 warning due to new way for loading url patterns.

### CODE REVIEW

**Comment by jieter** [comment]
Duplicate of #692

**Comment by drxos** [comment]
Great.

**Comment by sehmaschine** [comment]
fixed with stable/2.8.x

**Comment by drxos** [comment]
Good. I'll update my package

**Comment by sehmaschine** [comment]
@drxos please note that full compatibility with Django 1.9 is not yet given.

**Comment by drxos** [comment]
Ok. Don't forget to let me know if you need help. Keep in touch.

**Pull request closed without merging**
