### PR TITLE
Use localized datepickers for date input fields in Grappelli

### PR DESCRIPTION
**Pull request by mpasternak**
Hi,

thank you for sharing & maintaining this great, hiqh-quality, useful Django package.

I found some support for localized (i18n) datepickers in Grappelli, but they did not seem to work for me. So, I created this small patch. I'd be more than happy if you merged it. 

I used {% if LANGUAGE_CODE %} to test for i18n support, but I don't know if this is the best way.

### CODE REVIEW

**Comment by sehmaschine** [comment]
@mpasternak I've given this another try, but ... when you look at the django example with "de_AT" which is represented as "de-at" with the frontend, no such datepicker file exists which leads to a 404. Besides, the same is true with "pt_BR" (because the jquery UI file contains uppercase characters).

**Comment by mpasternak** [comment]
Would you like to distribute calendar locale files together with grappelli
or to have them in separate package?

In my projects, I use django-bower (which is just a tiny layer over bower)
for downloading javascript dependencies, but I think that for grappelli it
could be overkill.

In my "localized calendar" branch, I keep the locale file inside grappelli
source tree. If this is what we decide for the main branch (to keep the
locale files in grappelli source tree) - and, IMO, this is not a bad option
- I can rename them to match to Django locale codes.

Also, if you ask me - having uppercase letters in file names is a possible
problem with portability. We all know, that Windows doesn't care about
upper/lower case and in the past, there were some problems with file names,
especially those shorter, than 8 characters.



2015-01-02 15:20 GMT+01:00 Patrick Kranzlmueller <notifications@github.com>:

> @mpasternak <https://github.com/mpasternak> I've given this another try,
> but ... when you look at the django example with "de_AT" which is
> represented as "de-at" with the frontend, no such datepicker file exists
> which leads to a 404. Besides, the same is true with "pt_BR" (because the
> jquery UI file contains uppercase characters).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sehmaschine/django-grappelli/pull/528#issuecomment-68529251>
> .
>



-- 
Pozdrawiam,
Michał Pasternak
📱 +48 793 66 87 33

**Comment by sehmaschine** [comment]
I prefer to have the locale files with grappelli – but only if we don't need to rename the files (because renaming makes every jQuery update more difficult than necessary).

**Comment by mpasternak** [comment]
OK, this sounds reasonable. As a maintainer of a software package, that
consists of many elements, this sounds perfectly reasonable.

From my point of view, on the other hand, if I want locale codes from
Django to be translated to locale codes of jquery, I need to write some
code, to get the result from a mapping. Maybe I am not aware of some
simpler method, correct me if I am wrong, but it looks like it either
requires some extra JavaScript code, or a template tag or some middleware
stuff. And, as a result, we will be running a line of code just to serve a
static file, just to translate its name from one version to another.

As the locale files will not be updated too often (and, as the locale stuff
is only for calendar - at least, for now) - I suggest that we just rename
them and add them to the repository. If you disagree with this approach as
it will possibly make things harder to maintain in the future, please let
me know what solution would you like more: javascript code, middleware
modification (adding some extra parameters to request) or a template tag.
Or, a custom view (but using a custom Django view, running Python code, to
serve a small static file seems not optimal to me).

... or, in case there are some more methods, let me know.

2015-01-05 14:19 GMT+01:00 Patrick Kranzlmueller <notifications@github.com>:

> I prefer to have the locale files with grappelli – but only if we don't
> need to rename the files (because renaming makes every jQuery update more
> difficult than necessary).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sehmaschine/django-grappelli/pull/528#issuecomment-68706293>
> .
>



-- 
Pozdrawiam,
Michał Pasternak
📱 +48 793 66 87 33

**Comment by camilonova** [comment]
This is so annoying, I'm getting 500 errors because sometimes grappelli is looking for the en-us localized file and I have many locales active on the site, could be any random language and I don't want to add all the file languages.

At least can we silently move on if the file does not exist? 

My file storage check that every referenced file must exists, so I cannot live with a 404 on those files.

Can I help somehow to fix this?

**Comment by mpasternak** [comment]
Well, what solution would suit you, Camilo?

2015-02-04 21:56 GMT+01:00 Camilo Nova <notifications@github.com>:

> This is so annoying, I'm getting 500 errors because sometimes grappelli is
> looking for the en-us localized file and I have many locales active on the
> site, could be any random language and I don't want to add all the file
> languages.
>
> At least can we silently move on if the file does not exist?
>
> My file storage check that every referenced file must exists, so I cannot
> live with a 404 on those files.
>
> Can I help somehow to fix this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sehmaschine/django-grappelli/pull/528#issuecomment-72937128>
> .
>



-- 
Pozdrawiam,
Michał Pasternak
📱 +48 793 66 87 33

**Comment by camilonova** [comment]
What about non localizing the calendar widget, make it English by default and let anyone who need the localized version to replace it?

I guess most of the people don't need the localized calendar.

What do you think?

**Comment by msamoylov** [comment]
BTW, with grappelli 2.5.6 I'm getting this:

`ValueError: The file 'grappelli/jquery/i18n/ui.datepicker-en-us.js' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x2d61550>.`

**Comment by camilonova** [comment]
@msamoylov thats my problem too.

**Comment by camilonova** [comment]
@mpasternak any thoughts ?

**Comment by msamoylov** [comment]
I created a separate issue for that: https://github.com/sehmaschine/django-grappelli/issues/577

**Comment by mpasternak** [comment]
I'd add an empty file for en-us locale. If used in production with tools
like django-compresor, there is no overhead. What do you think?
5 mar 2015 22:47 "Camilo Nova" <notifications@github.com> napisał(a):

**Comment by sehmaschine** [comment]
I'm with @camilonova here, because there doesn't seem to be a clean solution. Stay with en and let people take care about translations (it's pretty easy anyway).

**Comment by mpasternak** [comment]
I'll take care of this.

Thank you guys for all the feedback and support.
6 mar 2015 09:33 "Patrick Kranzlmueller" <notifications@github.com>
napisał(a):

**Comment by camilonova** [comment]
Great, thanks.

**Comment by mpasternak** [comment]
Hi guys,

first of all, thank you very much for all your suggestions,

second, thank you very much for caring about such a great piece of software like django-grappelli.

I have did some plumbing in order to:
* fix @sehmaschine problem with "de-at" locale,
* fix @camilonova problem with file-not-found,
* include new translations,
* fail gracefully,
* be tolerant if LANGUAGE_CODE in settings.py wrong.

Please check my latest commits. Thanks!

**Comment by sehmaschine** [comment]
Closing this issue. please refer to #577 for the 500 ... other than that, we decided to not include the translation files because of the issues mentioned before. thanks everyone for participating and thanks for the thoughts/patches. I'm sorry that we are not able to include this ... but there doesn't seem to be a straightforward and maintainable solution.

**Comment by mpasternak** [comment]
Hey Patrick,

no offence taken,

I'm doing Django stuff for some time (as in ~5 yrs or so) and I've already
had enough trouble with deployment, I realize that there's a magnitude of
sites out there and it is pretty easy to break something for someone else
with a setup I've never thought of,

thanks to wonderful tools at github, it's trival to keep an up-to-date
patch in my branch. If you ever decide support it or to include it, you
know where to find me.

Regards,

2015-03-12 15:48 GMT+01:00 Patrick Kranzlmueller <notifications@github.com>:

> Closing this issue. please refer to #577
> <https://github.com/sehmaschine/django-grappelli/issues/577> for the 500
> ... other than that, we decided to not include the translation files
> because of the issues mentioned before. thanks everyone for participating
> and thanks for the thoughts/patches. I'm sorry that we are not able to
> include this ... but there doesn't seem to be a straightforward and
> maintainable solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sehmaschine/django-grappelli/pull/528#issuecomment-78494248>
> .
>



-- 
Pozdrawiam,
Michał Pasternak
📱 +48 793 66 87 33

**Pull request closed without merging**
