### PR TITLE
Show HTML on related labels

### LINKED ISSUE #847: Regression: HTML not supported in related labels
#197 added the ability to use HTML in related labels. This commit broke that ability by inserting using `.text()`: b2e45db1fa42e3c64fc226180960cc7ed437e3e6

### PR DESCRIPTION
**Pull request by ipmb**
Fixes #847

### CODE REVIEW

**Comment by ipmb** [comment]
I realize this may present a security problem in some contexts. Perhaps a better solution would be to update the data structure that is returned to say if the string is marked safe or not. Alternatively, firing a JS event here would let us hook in and modify the results.

**Comment by sehmaschine** [comment]
@ipmb thanks for the PR. I'm not sure about adding this though. As you mentioned it might be a security issue. And I can't remember why we removed the functionality. Triggering a JS event might be a solution – on the other hand it means that you have to write custom JS in order to show the HTML. That said, adding these events is probably a good idea anyway. Any preference with regards to the naming of these events? And we should probably add pre/post events, right? Like `preAddedRelatedFK` and `postAddedRelatedFK`.

**Comment by ipmb** [comment]
For my use case, the `post` is all that is necessary. I can't think of any reason for the `pre`, but I suppose it doesn't hurt to add it. They should probably be prefixed with something like `grappelli.`

What do you think about testing if the label is a safe string and passing that information to the front-end in the data structure?

**Comment by sehmaschine** [comment]
Ok. I see. But that does only make sense with related items (not autocompletes). Do you agree?

**Comment by ipmb** [comment]
I could see an argument for both, but just having them on related items is enough for me :)

**Comment by sehmaschine** [comment]
OK. I'll think about it – at the end it should be a solution which works for everyone (not just for your usecase). I'm not sure about autocompletes and it is probably a bit complicated as well.

**Pull request closed without merging**
