### PR TITLE
Updated django-smuggler template #512

### LINKED ISSUE #512: compatibility with django-smuggler
see #327

### PR DESCRIPTION
**Pull request by nemesisdesign**
Updated django-smuggler template in order to work with django-smuggler==0.6.0
Related/will fix #512

### CODE REVIEW

**Comment by sehmaschine** [comment]
@nemesisdesign which version of grappelli are you targeting?

**Comment by nemesisdesign** [comment]
I've tested it on 2.6.5, I noticed you just released 2.7.1, I'll test it on that release and come back to you in a couple of hours.

**Comment by nemesisdesign** [comment]
It works on 2.7.1 too. I synced the patch branch with the current master.

**Comment by sehmaschine** [comment]
@nemesisdesign thanks for the clarification.

**Comment by nemesisdesign** [comment]
@sehmaschine very welcome

**Comment by nemesisdesign** [comment]
Any issue with merging this?

**Comment by sehmaschine** [comment]
just merging pull requests ... will happen today.

**Comment by nemesisdesign** [comment]
:+1: thanks

**Pull request merged**
