### PR TITLE
If a twice add and more on updating (creating) in inline forms, then gives error non unique id of item.

### PR DESCRIPTION
**Pull request by cleverid**
VERSIONS: Grappelli 2.13.1, Django 2.2.3
STATICFILES: OK
JAVASCRIPTS: OK
CUSTOMIZATIONS: NONE

If a click add button twice and more in inline forms then django say on save action what id`s of inline item non unique. 
In code for create new item does copy empty hidden item, but unique id placed in value attribure of form not changed. 
Was added code wich generate new uuid and renew him in item.

This bag has django project too.

### CODE REVIEW

**Comment by sehmaschine** [comment]
sorry, can't follow this issue. besides, the patch seems a bit strange to me. I'm not sure this issue (if it actually _is_ an issue) should be handled with `updateFormIndex` instead. However, in order to work on this I need a better understanding of what's happening ... replacing ids is not a valid option IMO.

**Comment by cleverid** [comment]
I will try to understand this issue more deeply. And I will send a demo with an error. Ок?

**Comment by sehmaschine** [comment]
Not sure what you mean with demo, but a deeper understanding is a good idea in my opinion.

**Comment by sehmaschine** [comment]
closing this for now since I'm not able to reproduce this.

**Pull request closed without merging**
