### PR TITLE
Add Ukrainian translations for TinyMCE plugins

### PR DESCRIPTION
**Pull request by jTiKey**
Added Ukrainian translations for TinyMCE's search/replace, advanced hr, media, and fullpage plugins. This improves user experience for Ukrainian language users by providing them with translated plugin interfaces.

### CODE REVIEW

**Comment by sehmaschine** [comment]
I'm sorry, but there are currently no other languages than EN (with grappelli) – simply because it's too much effort to maintain that. But you can (pretty easily) add that to your local setup.

**Comment by jTiKey** [comment]
It wasn't that easy to add it. I had to find an ancient version of tiny_mce and put the files into appropriate folders. Oh well, I'll just save it in my fork then.

**Comment by sehmaschine** [comment]
Alright, I understand. But please note that we'll remove TinyMCE altogether with the next bigger milestone (this is already mentioned with the docs).

**Comment by jTiKey** [comment]
I see, makes sense then. Thanks for the explanation.

**Pull request closed without merging**
