### PR TITLE
fix issue with footer overlap when using GeoDjango

### PR DESCRIPTION
**Pull request by micrypt**
screen shot 2015-03-27 at 22 43 59

### CODE REVIEW

**Comment by parsch** [comment]
@micrypt Did you check the new footer z-index it with all other z-indizes throughout?

**Comment by micrypt** [comment]
@parsch I've only proposed to match it to that for `header#grp-header`. That said, I didn't notice any subsequent conflicts. This is really just me bringing it to your attention. I'll defer to your expertise.

**Comment by parsch** [comment]
@micrypt Just have to check some possible interferences. What's the z-index of the map? I don't have any GeoDjango stuff installed so let's find out theoretically.

**Comment by parsch** [comment]
@micrypt Can you tell me the z-index of the map?

**Comment by micrypt** [comment]
@parsch 

`div.olMap {  z-index: 0; }`

**Comment by parsch** [comment]
@micrypt That can't be: z-index 0 can't overlap z-index 900 (as the footer was positioned before your patch), can you take a second look maybe at ohter elements wrapping the map and having z-indices?

**Comment by micrypt** [comment]
@parsch That's the enclosing tag for the map. Open Layers then adds style attributes with z-indices well North of that value for some elements. Highest I've found so far was 1004. Looks like it's simply not well-behaved. Think I'll close this unless anyone else is interested.

**Comment by parsch** [comment]
@micrypt Right, thanks for clarifying. If we don't know the highest possible z-index it's a bit dangerous to operate with just something, I don't want to carelessly adjust z-indizes as some other features depend on that.

**Pull request closed without merging**
