### PR TITLE
Fix related object lookup popup

### LINKED ISSUE #593: New RelatedObjectLookups.js in d1.8 causing related object functions to stop working
In Django 1.8 some of the functions in `RelatedObjectLookups.js` got changed which caused their functionality to stop working. eg. while adding a new related object the popup does not show.

### PR DESCRIPTION
**Pull request by ngzhian**
Made this PR as a copy of #595 to base the commits on dev/2.7.x.

This is an attempt to fix #593 .
I'm trying to approach this in a number of steps1
1. Bring all the functions from `RelatedObjectLookups.js` in 1.8 into this repo
2. Get your comments on which functions can stay and which can go (elaboration below)
3. Finally fix the actual issue

More on 2. I've only been a user of grappelli, so I'm not too familiar with the piping that powers grappelli. Would like comments on the file itself to say which lines can stay and which lines can go. Note that the current pull request is ugly, has lots of comments saying if the code came from 1.8 `/* 18 */` or was originally there `/* grap */`. This is to help identify which portions of code came from where.
Eventually this PR can be squashed into a single commit to make the history cleaner.
Appreciate any comments, thanks!

### CODE REVIEW

**Comment by m-aciek** [comment]
Beg you to merge that!

**Comment by ngzhian** [comment]
@sehmaschine ping for this. What's left is to decide which functions should stay and which should go. The code is pretty well committed as to which function was introduced in django 1.8, so let me know which ones are safe to remove.
I'll patch this up with a commit that throws away methods I think are irrelevant, and hopefully that will be a better merge candidate. Thanks @m-aciek for bumping this up :facepunch:

**Comment by sehmaschine** [comment]
I'm currently taking a look. Unfortunately, I'm not able to merge this since some stuff is missing with RelatedObjetcLookups.js.

**Comment by ngzhian** [comment]
@sehmaschine got it, I tried my best to copy over all methods that were in django1.8, dedup all those functions we already have on grappelli, and commented the appropriate options. Let me know if I can help with anything else.

**Comment by sehmaschine** [comment]
should be solved with dev/2.7.x and stable/2.7.x ... please reopen if the issue still exists.

**Pull request closed without merging**
