### PR TITLE
Improved CSS for messages with HTML inside

### PR DESCRIPTION
**Pull request by r3m0t**
I'm creating a message (level INFO) that says:

```python
        SLOW_SEARCH_MESSAGE = mark_safe(_(
            'Your search was slow. You can speed it up by: <ol>'
            '<li>searching just for an email address,</li>'
            '<li>searching by name (at least two names), or</li>'
            '<li>applying more drop-down filters before searching</li></ol>'
        ))
```

Unfortunately the `li` in the messages pick up the same style (border especially) as the message box itself.

This will fix it.

### CODE REVIEW

**Comment by sehmaschine** [comment]
any specific reason you did not add the compiled css file?

**Comment by r3m0t** [comment]
I cheekily made the entire PR on github's website. I'll download and try it out now.

**Comment by r3m0t** [comment]
I tested 4d7a1a8f4550810f3f2a17c5b0b59e4b16aa873e

```
me:~/repos/project_name$ rg add_message
project_name/users/admin.py
43:        messages.add_message(request, messages.INFO, mark_safe('search faster:<ol><li>good option, or</li><li>less good option</li></ol>'))
```

screen shot 2017-10-05 at 16 33 29

**Comment by r3m0t** [comment]
I tested 2.10.2:
screen shot 2017-10-05 at 16 35 58

**Comment by sehmaschine** [comment]
@parsch can you confirm that this patch looks reasonable?

**Comment by parsch** [comment]
looks good

**Comment by sehmaschine** [comment]
added this to stable/2.10.x

**Pull request closed without merging**
